[package]
name = "parcel"
version = "0.1.0"
authors = ["Nathan"]

[dependencies]
esparse = { path = ".." }
crossbeam = "0.2"
num_cpus = "1.6"
matches = "0.1"
json = "0.11"
notify = "4.0"
memchr = "1.0.1"
