[package]
name = "parcel"
version = "1.0.0"
authors = ["Nathan"]

description = "Crate renamed to pax."
repository = "https://github.com/nathan/pax"
homepage = "https://crates.io/crates/pax"
license = "MIT"
readme = "../README.md"

keywords = []
categories = []
include = []

[dependencies]
